### ISSUE TITLE
Error with timezones during datetime subtraction

### ISSUE THREAD

**Issue by bdice** [LaurenceMolloy/RepoDash#14]
https://github.com/LaurenceMolloy/RepoDash/blob/aef0a0aed9ee48d752e785bd69f85d6c28524a61/src/GithubIssues.py#L627

I get an error on this line, resulting in the following output:
```
======== SQL EXCEPTION - START ========
('Timestamp subtraction must have the same timezones or no timezones', 'occurred at index opened_date')
========= SQL EXCEPTION - END =========
```

I will submit a PR to fix this.

**Comment by LaurenceMolloy** [comment]
Closing as now solved with commit #24
