### ISSUE TITLE
Add ability to save plot from the commandline

### ISSUE THREAD

**Issue by philippjfr** [LaurenceMolloy/RepoDash#23]
RepoDash is a great tool, to make it more useable for automated reporting it would be great if the CLI offered an option to save the generated plot to disk rather than opening an interactive window.

**Comment by LaurenceMolloy** [comment]
Ack that, Philipp. Thanks for your feedback.

Laurence

**Comment by LaurenceMolloy** [comment]
Save-to-file functionality now implemented and pushed to dev branch.
https://github.com/LaurenceMolloy/RepoDash/tree/dev

'-s filename' is the option you want
defaults to metrics.png if filename unspecified
outputs to window image (as before) if -s absent

Details added to user guide in githubio pages: 
https://github.com/LaurenceMolloy/RepoDash/blob/dev/docs/userguide.md

I would be grateful for a confirmatory test before merging into master.

**Comment by LaurenceMolloy** [comment]
Merged from dev branch in release v0.3 
Commit: 2ebb5a95294515b4d7ab0c6399ef221a81ef6b49
